import { useState } from "react";
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import { Download, LoaderCircle } from "lucide-react";
import { PDFDocument } from "pdf-lib";
import { PdfUploader, PdfPreview } from "@/components/ui/PdfUploader";
import { baseFileName, downloadBlob, extractPdfText, parsePageRanges } from "@/tools/pdf-utils";

export default function PdfToWord() {
  const [file, setFile] = useState<File | null>(null);
  const [pageCount, setPageCount] = useState(0);
  const [pageInput, setPageInput] = useState("all");
  const [includePageHeadings, setIncludePageHeadings] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [progressLabel, setProgressLabel] = useState("");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [previewText, setPreviewText] = useState("");

  async function handleUpload(files: File[]) {
    const selectedFile = files[0];
    if (!selectedFile) return;

    setFile(selectedFile);
    setPreviewText("");
    setErrorMessage(null);
    setProgressLabel("");

    try {
      const pdf = await PDFDocument.load(await selectedFile.arrayBuffer());
      const pages = pdf.getPageCount();
      setPageCount(pages);
      setPageInput(`1-${pages}`);
    } catch {
      setPageCount(0);
      setPageInput("all");
      setErrorMessage("Unable to read this PDF.");
    }
  }

  async function handleConvert() {
    if (!file) return;
    if (processing) return;

    setProcessing(true);
    setErrorMessage(null);
    setProgressLabel("Preparing conversion...");

    try {
      const sourceBytes = new Uint8Array(await file.arrayBuffer());
      const selectedPages = parsePageRanges(pageInput, pageCount);

      if (selectedPages.length === 0) {
        setErrorMessage("Please enter a valid page range.");
        return;
      }

      const pageTexts = await extractPdfText(sourceBytes, selectedPages, (done, total) => {
        setProgressLabel(`Extracting text ${done}/${total}...`);
      });

      const children: Paragraph[] = [];
      const previewChunks: string[] = [];

      for (let index = 0; index < pageTexts.length; index += 1) {
        const pageNumber = selectedPages[index];
        const text = (pageTexts[index] ?? "").trim();

        if (includePageHeadings) {
          children.push(
            new Paragraph({
              heading: HeadingLevel.HEADING_2,
              children: [new TextRun(`Page ${pageNumber}`)],
            }),
          );
        }

        if (!text) {
          children.push(new Paragraph({ children: [new TextRun("")] }));
          previewChunks.push(`Page ${pageNumber}: [No text detected]`);
          continue;
        }

        const paragraphs = text
          .split(/\n{2,}/)
          .map((part) => part.replace(/\s*\n\s*/g, " ").trim())
          .filter(Boolean);

        if (paragraphs.length === 0) {
          children.push(new Paragraph({ children: [new TextRun(text)] }));
          previewChunks.push(text);
        } else {
          for (const paragraphText of paragraphs) {
            children.push(new Paragraph({ children: [new TextRun(paragraphText)] }));
            previewChunks.push(paragraphText);
          }
        }
      }

      if (children.length === 0) {
        children.push(new Paragraph({ children: [new TextRun("No text could be extracted.")] }));
      }

      const doc = new Document({
        creator: "ObsidianKit",
        title: `${baseFileName(file.name)} - Converted from PDF`,
        description: "Generated by ObsidianKit PDF to Word tool",
        sections: [{ children }],
      });

      setProgressLabel("Generating .docx file...");
      const blob = await Packer.toBlob(doc);
      downloadBlob(blob, `${baseFileName(file.name)}.docx`);

      setPreviewText(previewChunks.join("\n\n").slice(0, 3200));
      setProgressLabel("Conversion complete.");
    } catch (error) {
      console.error("PDF to Word failed", error);
      setErrorMessage("Failed to convert this PDF to Word.");
      setProgressLabel("");
    } finally {
      setProcessing(false);
    }
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="text-center mb-8">
        <p className="text-sm text-[var(--color-text-muted)]">
          Convert selected PDF pages into an editable Word document locally in your browser.
        </p>
      </div>

      {!file ? (
        <PdfUploader onUpload={handleUpload} multiple={false} />
      ) : (
        <div className="space-y-6 animate-in fade-in zoom-in-95 duration-300">
          <PdfPreview
            files={[file]}
            onRemove={() => {
              setFile(null);
              setPageCount(0);
              setPageInput("all");
              setProgressLabel("");
              setErrorMessage(null);
              setPreviewText("");
            }}
          />

          <div className="rounded-2xl border border-[var(--color-border-primary)] bg-[var(--color-bg-card)] p-6 space-y-5">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <div className="mb-2 flex items-center justify-between">
                  <label className="block text-xs font-medium text-[var(--color-text-secondary)]">Pages</label>
                  <span className="text-xs text-[var(--color-text-muted)]">Total: {pageCount || "-"}</span>
                </div>
                <input
                  type="text"
                  value={pageInput}
                  onChange={(event) => setPageInput(event.target.value)}
                  placeholder="all or 1-3, 6"
                  className="w-full rounded-xl border border-[var(--color-border-primary)] bg-[var(--color-bg-input)] px-4 py-3 text-sm text-[var(--color-text-primary)] outline-none focus:border-[var(--color-border-hover)]"
                />
              </div>

              <div className="flex items-end">
                <label className="inline-flex items-center gap-2 text-xs text-[var(--color-text-secondary)]">
                  <input
                    type="checkbox"
                    checked={includePageHeadings}
                    onChange={(event) => setIncludePageHeadings(event.target.checked)}
                    className="h-4 w-4 rounded border-[var(--color-border-primary)]"
                  />
                  Include page headings in DOCX
                </label>
              </div>
            </div>

            <button
              onClick={handleConvert}
              disabled={processing}
              className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--color-text-primary)] px-8 py-3.5 text-sm font-bold text-[var(--color-bg-primary)] transition-all hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {processing ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
              {processing ? "Converting..." : "Convert to Word & Download"}
            </button>

            {progressLabel && <p className="text-xs text-[var(--color-text-muted)]">{progressLabel}</p>}
            {errorMessage && <p className="text-xs text-red-500">{errorMessage}</p>}
          </div>

          {previewText && (
            <div className="rounded-2xl border border-[var(--color-border-primary)] bg-[var(--color-bg-card)] p-4 sm:p-5 space-y-3">
              <h3 className="text-sm font-semibold text-[var(--color-text-primary)]">Extract Preview</h3>
              <textarea
                value={previewText}
                readOnly
                rows={10}
                className="w-full resize-y rounded-xl border border-[var(--color-border-primary)] bg-[var(--color-bg-input)] px-4 py-3 text-sm leading-relaxed text-[var(--color-text-primary)]"
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
