import { lazy, type ComponentType } from "react";

/**
 * Tool registry: maps tool slugs to lazy-loaded components.
 * Only tools with actual implementations are registered here.
 * Tools without an entry will show the default placeholder in ToolPage.
 */
const registry: Record<string, React.LazyExoticComponent<ComponentType>> = {
  "word-counter": lazy(() => import("./word-counter/WordCounter")),
  "bmi-calculator": lazy(() => import("./bmi-calculator/BmiCalculator")),
  "password-generator": lazy(() => import("./password-generator/PasswordGenerator")),
  "length-converter": lazy(() => import("./length-converter/LengthConverter")),
  "volume-converter": lazy(() => import("./volume-converter/VolumeConverter")),
  "area-converter": lazy(() => import("./area-converter/AreaConverter")),
  "speed-converter": lazy(() => import("./speed-converter/SpeedConverter")),
  "data-storage-converter": lazy(() => import("./data-storage-converter/DataStorageConverter")),
  "currency-converter": lazy(() => import("./currency-converter/CurrencyConverter")),
  "cooking-converter": lazy(() => import("./cooking-converter/CookingConverter")),
  "time-converter": lazy(() => import("./time-converter/TimeConverter")),
  "percentage-calculator": lazy(() => import("./percentage-calculator/PercentageCalculator")),
  "compound-interest": lazy(() => import("./compound-interest/CompoundInterest")),
  "salary-calculator": lazy(() => import("./salary-calculator/SalaryCalculator")),
  "scientific-calculator": lazy(() => import("./scientific-calculator/ScientificCalculator")),
  "gpa-calculator": lazy(() => import("./gpa-calculator/GpaCalculator")),
  "tip-calculator": lazy(() => import("./tip-calculator/TipCalculator")),
  "fuel-economy": lazy(() => import("./fuel-economy/FuelEconomy")),
  "case-converter": lazy(() => import("./case-converter/CaseConverter")),
  "remove-duplicates": lazy(() => import("./remove-duplicates/RemoveDuplicates")),
  "find-replace": lazy(() => import("./find-replace/FindReplace")),
  "password-strength": lazy(() => import("./password-strength/PasswordStrength")),
  "url-encoder": lazy(() => import("./url-encoder/UrlEncoder")),
  "regex-tester": lazy(() => import("./regex-tester/RegexTester")),
  "color-picker": lazy(() => import("./color-picker/ColorPicker")),
  "qr-generator": lazy(() => import("./qr-generator/QrGenerator")),
  "image-to-text": lazy(() => import("./image-to-text/ImageToText")),
  "timezone-converter": lazy(() => import("./timezone-converter/TimezoneConverter")),
  "plagiarism-checker": lazy(() => import("./plagiarism-checker/PlagiarismChecker")),
  "age-calculator": lazy(() => import("./age-calculator/AgeCalculator")),
  "json-formatter": lazy(() => import("./json-formatter/JsonFormatter")),
  "base64-encoder": lazy(() => import("./base64-encoder/Base64Encoder")),
  "temperature-converter": lazy(() => import("./temperature-converter/TemperatureConverter")),
  "weight-converter": lazy(() => import("./weight-converter/WeightConverter")),
  "loan-calculator": lazy(() => import("./loan-calculator/LoanCalculator")),
  "png-to-jpg": lazy(() => import("./png-to-jpg/PngToJpg")),
  "jpg-to-png": lazy(() => import("./jpg-to-png/JpgToPng")),
  "webp-converter": lazy(() => import("./webp-converter/WebpConverter")),
  "image-resizer": lazy(() => import("./image-resizer/ImageResizer")),
  "image-rotator": lazy(() => import("./image-rotator/ImageRotator")),
  "image-cropper": lazy(() => import("./image-cropper/ImageCropper")),
  "exif-remover": lazy(() => import("./exif-remover/ExifRemover")),
  "watermark-adder": lazy(() => import("./watermark-adder/WatermarkAdder")),
  "merge-pdf": lazy(() => import("./merge-pdf/MergePdf")),
  "split-pdf": lazy(() => import("./split-pdf/SplitPdf")),
  "pdf-rotator": lazy(() => import("./pdf-rotator/PdfRotator")),
  "pdf-reorder": lazy(() => import("./pdf-reorder/PdfReorder")),
  "pdf-page-numbers": lazy(() => import("./pdf-page-numbers/PdfPageNumbers")),
  "protect-pdf": lazy(() => import("./protect-pdf/ProtectPdf")),
  "unlock-pdf": lazy(() => import("./unlock-pdf/UnlockPdf")),
  "pdf-metadata": lazy(() => import("./pdf-metadata/PdfMetadata")),
  "heic-to-jpg": lazy(() => import("./heic-to-jpg/HeicToJpg")),
  "image-compressor": lazy(() => import("./image-compressor/ImageCompressor")),
  "pdf-compressor": lazy(() => import("./pdf-compressor/PdfCompressor")),
  "background-remover": lazy(() => import("./background-remover/BackgroundRemover")),
  "pdf-editor": lazy(() => import("./pdf-editor/PdfEditor")),
  "pdf-to-word": lazy(() => import("./pdf-to-word/PdfToWord")),
  "word-to-pdf": lazy(() => import("./word-to-pdf/WordToPdf")),
  "pdf-ocr": lazy(() => import("./pdf-ocr/PdfOcr")),
  "pdf-to-image": lazy(() => import("./pdf-to-image/PdfToImage")),
  "pdf-to-txt": lazy(() => import("./pdf-to-txt/PdfToTxt")),
  "video-compressor": lazy(() => import("./video-compressor/VideoCompressor")),
  "video-trimmer": lazy(() => import("./video-trimmer/VideoTrimmer")),
  "video-resizer": lazy(() => import("./video-resizer/VideoResizer")),
  "mp4-to-avi": lazy(() => import("./mp4-to-avi/Mp4ToAvi")),
  "mp4-to-mov": lazy(() => import("./mp4-to-mov/Mp4ToMov")),
  "video-to-audio": lazy(() => import("./video-to-audio/VideoToAudio")),
  "video-to-gif": lazy(() => import("./video-to-gif/VideoToGif")),
  "frame-extractor": lazy(() => import("./frame-extractor/FrameExtractor")),
  "audio-compressor": lazy(() => import("./audio-compressor/AudioCompressor")),
  "mp3-to-wav": lazy(() => import("./mp3-to-wav/Mp3ToWav")),
  "audio-speed-changer": lazy(() => import("./audio-speed-changer/AudioSpeedChanger")),
};

export function getToolComponent(
  slug: string,
): React.LazyExoticComponent<ComponentType> | null {
  return registry[slug] ?? null;
}

export default registry;
